// <auto-generated />
namespace WebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Inclusa_Campo_Username_Model_Tareras : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inclusa_Campo_Username_Model_Tareras));
        
        string IMigrationMetadata.Id
        {
            get { return "201609282251149_Inclusa_Campo_Username_Model_Tareras"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
